import{describe,it}from'node:test';
import assert from'node:assert/strict';
import{authCredentials,authErrorMessage,calculateSummary,storageFileName,validateInvoiceFile}from'./data.js';
import{parseInvoiceText}from'./ocr.js';
describe('calculateSummary',()=>{it('counts each transaction once and separates monthly totals',()=>{const rows=[{kind:'income',amount:2000,occurred_on:'2026-09-01'},{kind:'expense',amount:350,occurred_on:'2026-09-02'},{kind:'expense',amount:100,occurred_on:'2026-08-31'}];const r=calculateSummary(rows,[{status:'to_pay'},{status:'to_review'}],'2026-09');assert.equal(r.income,2000);assert.equal(r.expenses,350);assert.equal(r.balance,1550);assert.equal(r.unpaid.length,1);assert.equal(r.review.length,1)})});
describe('authCredentials',()=>{it('never turns an empty signup into an anonymous request',()=>{assert.deepEqual(authCredentials({email:'',password:''}),{error:'Inserisci email e password.'})});it('normalizes valid credentials',()=>{assert.deepEqual(authCredentials({email:'  klajdi@example.com ',password:'12345678'}),{email:'klajdi@example.com',password:'12345678'})})});
describe('authErrorMessage',()=>{it('explains invalid credentials to a first-time user',()=>{assert.match(authErrorMessage('Invalid login credentials'),/Crea account/)})});
describe('invoice documents',()=>{it('accepts supported files and rejects unsafe input',()=>{assert.equal(validateInvoiceFile({type:'application/pdf',size:1000}),'');assert.match(validateInvoiceFile({type:'text/html',size:1000}),/soltanto/);assert.match(validateInvoiceFile({type:'image/jpeg',size:10485761}),/10 MB/)});it('creates a storage-safe file name',()=>{assert.equal(storageFileName('Fattura luce settembre 2026.pdf'),'Fattura-luce-settembre-2026.pdf')})});
describe('invoice OCR',()=>{it('extracts financial fields without marking the invoice paid',()=>{const result=parseInvoiceText('Fornitore: Energia Italia SRL\nNumero fattura: FT-2026/88\nData documento: 14/09/2026\nScadenza: 30/09/2026\nIUV: 1234 5678 9012 345\nTotale da pagare € 1.234,56');assert.equal(result.extracted.supplier,'Energia Italia SRL');assert.equal(result.extracted.amount,1234.56);assert.equal(result.extracted.invoice_number,'FT-2026/88');assert.equal(result.extracted.iuv,'123456789012345');assert.equal(result.extracted.issued_on,'2026-09-14');assert.equal(result.extracted.due_on,'2026-09-30');assert.equal('status'in result.extracted,false)})});
