import{createClient}from'@supabase/supabase-js';
import{createIcons,icons}from'lucide';
import{authCredentials,authErrorMessage,bankBalanceSummary,budgetProgress,calculateSummary,mergeFinancialExtractions,money,parseBankCsv,safeText,spendingInsights,storageFileName,uncategorizedBankTransactions,validateInvoiceFile}from'./data.js';
import'./styles.css';
import'./email.css';

const pages=[['Home','LayoutDashboard'],['Fatture','FileText'],['Email','Mail'],['Entrate','TrendingUp'],['Spese','TrendingDown'],['Banca','Landmark'],['Da classificare','Tags'],['Riepilogo','Rows3'],['Scadenze','CalendarClock'],['Statistiche','ChartNoAxesCombined'],['Backup','DatabaseBackup'],['Impostazioni','Settings']];
const envUrl=import.meta.env.VITE_SUPABASE_URL,envKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY;
const cloudReady=Boolean(envUrl&&envKey&&!envUrl.includes('YOUR_PROJECT'));
const supabase=cloudReady?createClient(envUrl,envKey):null;
const VAPID_PUBLIC_KEY='BMrKPlKuLA8-2y-7agapE4xBkp0_8wMcFZ9pL42Lalj8PIUwTQ1bOQXEudUpMrG3nXwfUZQCvhnLfc_WNybt3-M';
const state={page:'Home',session:null,transactions:[],invoices:[],categories:[],budgets:[],accounts:[],bankConnections:[],bankInstitutions:[],emailAccounts:[],emails:[],attachments:[],notifications:[],busy:false,error:'',notice:'',authEmail:'',autoSyncStarted:false,bankSyncStarted:false,gmailSyncing:false,autoOcrAttempted:new Set()};
const app=document.querySelector('#app'),ico=n=>`<i data-lucide="${n}" aria-hidden="true"></i>`,draw=()=>createIcons({icons});
const date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('it-IT'):'—';
const status=s=>({paid:'PAGATA',to_pay:'DA PAGARE',to_review:'DA CONTROLLARE'}[s]||s);

function setPage(page){state.page=page;state.error='';render()}
async function loadData(){
  if(!supabase||!state.session)return;
  state.busy=true;render();
  const[tx,inv,cat,budgets,accounts,bankConnections,emailAccounts,emails,attachments,notifications]=await Promise.all([
    supabase.from('transactions').select('*,categories!transactions_category_id_fkey(name)').order('occurred_on',{ascending:false}),
    supabase.from('invoices').select('*,categories!invoices_category_id_fkey(name)').order('due_on',{ascending:true}),
    supabase.from('categories').select('*').order('name'),
    supabase.from('budgets').select('*').order('created_at'),
    supabase.from('accounts').select('*').order('created_at'),
    supabase.from('bank_connections').select('*').order('created_at'),
    supabase.from('email_accounts').select('*').eq('user_id',state.session.user.id).order('created_at'),
    supabase.from('emails').select('*').eq('user_id',state.session.user.id).not('financial_status','is',null).order('received_at',{ascending:false}).limit(100),
    supabase.from('attachments').select('*').eq('user_id',state.session.user.id).not('email_id','is',null).order('created_at'),
    supabase.from('notifications').select('*').eq('user_id',state.session.user.id).is('read_at',null).order('created_at',{ascending:false}).limit(20)]);
  const failed=[tx,inv,cat,budgets,accounts,bankConnections,emailAccounts,emails,attachments,notifications].find(x=>x.error)?.error;
  if(failed)state.error=failed.message;else{state.transactions=tx.data;state.invoices=inv.data;state.categories=cat.data;state.budgets=budgets.data;state.accounts=accounts.data;state.bankConnections=bankConnections.data;state.emailAccounts=emailAccounts.data;state.emails=emails.data;state.attachments=attachments.data;state.notifications=notifications.data}
  state.busy=false;render();
  if(state.emailAccounts.length&&!state.autoSyncStarted){state.autoSyncStarted=true;setTimeout(()=>{enablePush(false);syncRecentEmails(null,true)},500)}
  if(state.accounts.some(account=>account.external_provider==='enablebanking')&&!state.bankSyncStarted){state.bankSyncStarted=true;setTimeout(()=>syncBanks(true),900)}
}

function authView(){
  app.innerHTML=`<main class="auth-shell"><section class="auth-card"><div class="brand large"><span>${ico('WalletCards')}</span>SOLDI</div><p class="kicker">IL TUO SPAZIO FINANZIARIO</p><h1>Tutto sotto controllo.</h1><p class="auth-copy">Accedi per gestire entrate, spese, fatture e scadenze in uno spazio personale protetto.</p>${!cloudReady?'<div class="alert warning">Configurazione cloud non completata. Aggiungi le variabili Supabase al progetto Vercel.</div>':''}${state.error?`<div class="alert">${safeText(state.error)}</div>`:''}<form id="auth-form"><label>Email<input type="email" name="email" autocomplete="email" value="${safeText(state.authEmail)}" required></label><label>Password<input type="password" name="password" autocomplete="current-password" minlength="8" required></label><button class="primary wide" ${!cloudReady?'disabled':''}>Accedi con account esistente</button><button class="secondary wide" type="button" id="signup" ${!cloudReady?'disabled':''}>Prima volta? Crea account</button></form><p class="legal">I dati sono separati per utente tramite policy di sicurezza del database.</p></section></main>`;
  draw();if(!cloudReady)return;
  const form=document.querySelector('#auth-form');
  form.onsubmit=e=>authenticate(e,false);
  document.querySelector('#signup').onclick=()=>{if(form.reportValidity())authenticate({preventDefault(){},currentTarget:form},true)};
}
async function authenticate(event,signup){
  event.preventDefault();state.error='';const form=event.currentTarget;
  if(!form.reportValidity())return;
  const credentials=authCredentials(Object.fromEntries(new FormData(form)));
  if(credentials.error){state.error=credentials.error;authView();return}
  const{email,password}=credentials;
  state.authEmail=email;
  const result=signup?await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword({email,password});
  if(result.error){state.error=authErrorMessage(result.error.message);authView()}else if(signup&&!result.data.session){state.error='Account creato. Controlla la tua email per confermare l’accesso.';authView()}
}

function shell(content){
  const user=state.session.user;
  app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span>${ico('WalletCards')}</span>SOLDI</div><nav>${pages.map(([label,glyph])=>`<button data-page="${label}" class="${state.page===label?'active':''}">${ico(glyph)}<span>${label}</span></button>`).join('')}</nav><div class="account"><div class="avatar">${safeText(user.email[0].toUpperCase())}</div><div><strong>${safeText(user.email.split('@')[0])}</strong><small>${safeText(user.email)}</small></div><button id="logout" title="Esci">${ico('LogOut')}</button></div></aside><main class="workspace"><header><button class="menu" id="menu">${ico('Menu')}</button><div><p class="kicker">GESTIONE FINANZIARIA</p><h1>${state.page}</h1></div><div class="cloud-state">${ico('Cloud')}<span>Cloud attivo</span></div></header>${state.notice?`<div class="alert success">${safeText(state.notice)}</div>`:''}${state.error?`<div class="alert">${safeText(state.error)}</div>`:''}${state.busy?'<div class="loader">Sincronizzazione…</div>':''}<section>${content}</section></main><button class="scrim" id="scrim" aria-label="Chiudi menu"></button></div>`;
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  document.querySelector('#menu').onclick=()=>document.querySelector('.app-shell').classList.add('menu-open');
  document.querySelector('#scrim').onclick=()=>document.querySelector('.app-shell').classList.remove('menu-open');
  document.querySelector('#logout').onclick=()=>supabase.auth.signOut();draw();
}
function metric(label,value,glyph,tone=''){return`<article class="metric"><div class="metric-icon ${tone}">${ico(glyph)}</div><p>${label}</p><strong class="${tone}">${value}</strong><small>Aggiornato dal database</small></article>`}
function empty(message){return`<div class="empty">${ico('Inbox')}<p>${message}</p></div>`}
function txRows(rows,manage=false){return rows.length?`<div class="rows">${rows.map(t=>`<div class="row"><div class="row-icon ${t.kind}">${ico(t.is_transfer?'ArrowLeftRight':t.kind==='income'?'ArrowDownLeft':'ArrowUpRight')}</div><div><strong>${safeText(t.description)}</strong><small>${date(t.occurred_on)} · ${t.is_transfer?'Trasferimento tra conti':safeText(t.categories?.name||'Senza categoria')}</small></div><div class="align-right"><b class="${t.is_transfer?'':t.kind==='income'?'positive':'negative'}">${t.is_transfer?'↔ ':t.kind==='income'?'+':'−'}${money(t.amount)}</b>${manage&&!t.is_transfer?`<button class="document-button" data-categorize="${t.id}">${ico('Tags')} Categoria</button>`:''}</div></div>`).join('')}</div>`:empty('Nessun movimento registrato.')}
function categoryDialogMarkup(){return`<dialog id="category-dialog"><form id="category-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">CORREGGI CATEGORIA</p><h2 id="category-title">Movimento</h2></div><button type="button" class="icon-button" id="close-category">${ico('X')}</button></div><input name="transaction_id" type="hidden"><label>Categoria<select name="category_id"></select></label><p class="form-note">Se è un movimento bancario, SOLDI ricorderà il negozio o fornitore e userà questa categoria in futuro.</p><button class="primary wide">Salva categoria</button></form></dialog>`}
function bindCategoryManagement(rows){
  const categoryDialog=document.querySelector('#category-dialog'),categoryForm=document.querySelector('#category-form');if(!categoryDialog||!categoryForm)return;document.querySelector('#close-category').onclick=()=>categoryDialog.close();
  document.querySelectorAll('[data-categorize]').forEach(button=>button.onclick=()=>{const transaction=rows.find(item=>item.id===button.dataset.categorize);if(!transaction)return;categoryForm.elements.transaction_id.value=transaction.id;categoryForm.elements.category_id.innerHTML=`<option value="">Senza categoria</option>${state.categories.filter(category=>category.kind===transaction.kind||category.kind==='both').map(category=>`<option value="${category.id}">${safeText(category.name)}</option>`).join('')}`;categoryForm.elements.category_id.value=transaction.category_id||'';document.querySelector('#category-title').textContent=transaction.description;categoryDialog.showModal()});
  categoryForm.onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(categoryForm)),submit=categoryForm.querySelector('[type="submit"]');submit.disabled=true;const{data,error}=await supabase.functions.invoke('transaction-category',{body:{transaction_id:values.transaction_id,category_id:values.category_id||null}});submit.disabled=false;if(error||!data?.updated){state.error=await functionError(error,data?.error||'Impossibile aggiornare la categoria.');categoryDialog.close();render();return}categoryDialog.close();const count=Number(data.updated_count||1);state.notice=data.learned?`Categoria imparata e applicata a ${count} moviment${count===1?'o':'i'} dello stesso negozio.`:'Categoria aggiornata.';await loadData()};
}
function invoiceRows(rows,manage=false){return rows.length?`<div class="rows">${rows.map(i=>`<div class="row"><div><strong>${safeText(i.supplier)}</strong><small>${date(i.due_on)} · ${safeText(i.invoice_number||'Senza numero')}${i.document_name?` · ${safeText(i.document_name)}`:''}</small></div><div class="align-right"><b>${money(i.amount)}</b><span class="badge ${i.status}">${status(i.status)}</span><div>${i.storage_path?`<button class="document-button" data-document="${i.id}">${ico('Paperclip')} Apri</button>`:''}${manage&&i.status==='to_pay'?`<button class="document-button" data-pay-invoice="${i.id}">${ico('BadgeCheck')} Segna pagata</button>`:''}${manage?`<button class="document-button" data-edit-invoice="${i.id}">${ico('Pencil')} Modifica</button><button class="document-button negative" data-delete-invoice="${i.id}">${ico('Trash2')} Elimina</button>`:''}</div></div></div>`).join('')}</div>`:empty('Nessuna scadenza aperta.')}
async function fileHash(file){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function bindInvoiceDocuments(){document.querySelectorAll('[data-document]').forEach(button=>button.onclick=async()=>{const invoice=state.invoices.find(item=>item.id===button.dataset.document);if(!invoice?.storage_path)return;button.disabled=true;const{data,error}=await supabase.storage.from('invoice-documents').download(invoice.storage_path);button.disabled=false;if(error){state.error=error.message;render();return}const url=URL.createObjectURL(data),link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.download=invoice.document_name||'fattura';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)})}
function invoiceFields(invoice={}){return`<div class="form-grid"><label>Fornitore<input name="supplier" value="${safeText(invoice.supplier||'')}" required maxlength="160"></label><label>Importo<input name="amount" type="number" min="0.01" step="0.01" value="${invoice.amount||''}" required></label><label>Numero fattura<input name="invoice_number" value="${safeText(invoice.invoice_number||'')}" maxlength="80"></label><label>IUV<input name="iuv" value="${safeText(invoice.iuv||'')}" maxlength="80"></label><label>Data documento<input name="issued_on" type="date" value="${invoice.issued_on||''}"></label><label>Scadenza<input name="due_on" type="date" value="${invoice.due_on||''}"></label></div><label>Stato<select name="status"><option value="to_review" ${invoice.status==='to_review'?'selected':''}>DA CONTROLLARE</option><option value="to_pay" ${invoice.status==='to_pay'?'selected':''}>DA PAGARE</option><option value="paid" ${invoice.status==='paid'?'selected':''}>PAGATA</option></select></label>`}
function bindInvoiceManagement(){
  const dialog=document.querySelector('#invoice-edit-dialog'),content=document.querySelector('#invoice-edit-content');if(!dialog||!content)return;
  document.querySelectorAll('[data-edit-invoice]').forEach(button=>button.onclick=()=>{const invoice=state.invoices.find(item=>item.id===button.dataset.editInvoice);if(!invoice)return;const extracted=invoice.extracted_data||{},ocrDetails=invoice.ocr_status==='complete'?`<div class="loader">OCR ${Math.round(Number(invoice.confidence||0)*100)}% · ${Object.values(extracted).filter(Boolean).length} campi proposti</div>`:'';content.innerHTML=`<form id="invoice-edit-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">VERIFICA FATTURA</p><h2>Modifica dati</h2></div><button type="button" class="icon-button" id="close-edit">${ico('X')}</button></div>${ocrDetails}${invoiceFields(invoice)}<p class="form-note">Se scegli “Pagata”, confermi manualmente di avere una prova del pagamento.</p><button class="primary wide">Salva modifiche</button></form>`;document.querySelector('#close-edit').onclick=()=>dialog.close();document.querySelector('#invoice-edit-form').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));values.amount=Number(values.amount);for(const key of['invoice_number','iuv','issued_on','due_on'])if(!values[key])values[key]=null;const{error}=await supabase.from('invoices').update(values).eq('id',invoice.id);if(error){state.error=error.message;dialog.close();render()}else{dialog.close();await loadData()}};dialog.showModal();draw()});
  document.querySelectorAll('[data-delete-invoice]').forEach(button=>button.onclick=async()=>{const invoice=state.invoices.find(item=>item.id===button.dataset.deleteInvoice);if(!invoice||!confirm(`Eliminare la fattura di ${invoice.supplier}?`))return;button.disabled=true;const attachment=await supabase.from('attachments').delete().eq('invoice_id',invoice.id);if(attachment.error){state.error=attachment.error.message;render();return}const deleted=await supabase.from('invoices').delete().eq('id',invoice.id);if(deleted.error){state.error=deleted.error.message;render();return}if(invoice.storage_path)await supabase.storage.from('invoice-documents').remove([invoice.storage_path]);await loadData()})
  document.querySelectorAll('[data-pay-invoice]').forEach(button=>button.onclick=async()=>{const invoice=state.invoices.find(item=>item.id===button.dataset.payInvoice);if(!invoice||!confirm(`Confermi di avere pagato ${money(invoice.amount)} a ${invoice.supplier}?`))return;button.disabled=true;button.textContent='Registrazione…';const{data,error}=await supabase.functions.invoke('invoice-mark-paid',{body:{invoice_id:invoice.id}});if(error||!data?.transaction_id){state.error=await functionError(error,data?.error||'Impossibile registrare il pagamento.');render();return}state.notice='Fattura pagata e spesa registrata una sola volta.';await loadData()})
}
function bindJumps(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setPage(b.dataset.jump))}

function home(){
  const s=calculateSummary(state.transactions,state.invoices),bank=bankBalanceSummary(state.accounts),due=state.invoices.filter(i=>i.status==='to_pay').slice(0,4),linkedEmailIds=new Set(state.invoices.map(i=>i.source_email_id).filter(Boolean)),emailToPay=state.emails.filter(e=>e.financial_status==='to_pay'&&!linkedEmailIds.has(e.id)).length,emailReview=state.emails.filter(e=>e.financial_status==='to_review'&&!linkedEmailIds.has(e.id)).length;
  shell(`<div class="metric-grid">${metric('Disponibile banche',bank.accounts.length?money(bank.total,bank.currency):'—','Wallet')}${metric('Entrate mese',money(s.income),'ArrowUpRight','positive')}${metric('Spese mese',money(s.expenses),'ArrowDownRight','negative')}${metric('Da pagare',s.unpaid.length+emailToPay,'ReceiptText','warning')}</div><div class="content-grid"><article class="panel"><div class="panel-head"><div><p class="kicker">ATTIVITÀ</p><h2>Ultimi movimenti</h2></div><button data-jump="Riepilogo">Vedi tutti</button></div>${txRows(state.transactions.slice(0,6))}</article><article class="panel"><div class="panel-head"><div><p class="kicker">AGENDA</p><h2>Prossime scadenze</h2></div><button data-jump="Scadenze">Apri</button></div>${invoiceRows(due)}</article></div><div class="content-grid compact"><article class="panel spotlight"><div>${ico('PiggyBank')}<p>Risparmio del mese</p><strong class="${s.savings>=0?'positive':'negative'}">${money(s.savings)}</strong></div><div class="spark"><span style="width:${Math.min(100,s.income?Math.max(0,s.savings/s.income*100):0)}%"></span></div></article><article class="panel review"><div><p class="kicker">RICHIEDE ATTENZIONE</p><h2>${s.review.length+emailReview} fatture da controllare</h2></div><button data-jump="Email" class="round">${ico('ArrowRight')}</button></article></div>`);bindJumps();draw();
}
function transactionPage(kind){
  const rows=state.transactions.filter(t=>t.kind===kind&&!t.is_transfer);
  const categoryOptions=state.categories.filter(c=>c.kind===kind||c.kind==='both').map(c=>`<option value="${c.id}">${safeText(c.name)}</option>`).join('');
  shell(`<div class="toolbar"><p>${rows.length} operazioni sincronizzate</p><button class="primary" id="new-tx">${ico('Plus')} Nuova ${kind==='income'?'entrata':'spesa'}</button></div><article class="panel table-panel">${txRows(rows,true)}</article><dialog id="tx-dialog"><form id="tx-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">NUOVA OPERAZIONE</p><h2>Registra ${kind==='income'?'entrata':'spesa'}</h2></div><button type="button" class="icon-button" id="close-dialog">${ico('X')}</button></div><label>Descrizione<input name="description" required maxlength="140"></label><div class="form-grid"><label>Importo<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Data<input name="occurred_on" type="date" value="${new Date().toISOString().slice(0,10)}" required></label></div><label>Categoria<select name="category_id"><option value="">Senza categoria</option>${categoryOptions}</select></label><label>Note<textarea name="notes" maxlength="500"></textarea></label><button class="primary wide">Salva nel cloud</button></form></dialog>${categoryDialogMarkup()}`);
  const dialog=document.querySelector('#tx-dialog');document.querySelector('#new-tx').onclick=()=>dialog.showModal();document.querySelector('#close-dialog').onclick=()=>dialog.close();
  document.querySelector('#tx-form').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));Object.assign(v,{kind,user_id:state.session.user.id,amount:Number(v.amount),category_id:v.category_id||null});const{error}=await supabase.from('transactions').insert(v);if(error){state.error=error.message;render()}else{dialog.close();await loadData()}};draw();
  bindCategoryManagement(rows);
}
function classificationPage(){const rows=uncategorizedBankTransactions(state.transactions);shell(`<div class="toolbar"><p>${rows.length} moviment${rows.length===1?'o':'i'} bancar${rows.length===1?'io':'i'} da classificare</p><button class="secondary" data-jump="Banca">${ico('RefreshCw')} Aggiorna banca</button></div><article class="panel table-panel"><div class="panel-head"><div><p class="kicker">SOLO SE SERVE</p><h2>Movimenti non riconosciuti</h2></div><small>SOLDI mostra qui soltanto le causali che non riesce a capire da solo.</small></div>${rows.length?txRows(rows,true):empty('Tutti i movimenti bancari sono già classificati.')}</article>${categoryDialogMarkup()}`);bindJumps();bindCategoryManagement(rows);draw()}
function invoicesPage(){
  const linkedEmailIds=new Set(state.invoices.map(invoice=>invoice.source_email_id).filter(Boolean)),pending=state.emails.filter(message=>message.financial_status==='to_pay'&&!linkedEmailIds.has(message.id));
  const pendingRows=pending.length?`<article class="panel table-panel"><div class="panel-head"><div><p class="kicker">DA PAGARE</p><h2>Rette e bollette senza importo</h2></div><small>L’importo non viene inventato: premi Completa per inserirlo.</small></div><div class="rows">${pending.map(message=>`<div class="row"><div><strong>${safeText(message.subject||'Pagamento familiare')}</strong><small>${safeText(message.extracted_data?.supplier||message.sender||'Mittente sconosciuto')} · ${message.received_at?new Date(message.received_at).toLocaleDateString('it-IT'):'—'} · Importo da inserire</small></div><div class="align-right"><span class="badge to_pay">DA PAGARE</span><button class="document-button" data-complete-email="${message.id}">Completa</button></div></div>`).join('')}</div></article>`:'';
  shell(`<div class="toolbar"><p>${state.invoices.length+pending.length} fatture e pagamenti familiari · documenti protetti</p><button class="primary" id="new-invoice">${ico('Plus')} Importa fattura</button></div>${pendingRows}<article class="panel table-panel">${invoiceRows(state.invoices,true)}</article><dialog id="invoice-dialog"><form id="invoice-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">NUOVO DOCUMENTO</p><h2>Importa fattura</h2></div><button type="button" class="icon-button" id="close-dialog">${ico('X')}</button></div><label>PDF o foto<input name="document" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"></label><p class="form-note file-hint">PDF, JPG, PNG o WEBP · massimo 10 MB · OCR eseguito sul dispositivo</p><div id="ocr-progress" class="loader" hidden></div>${invoiceFields({status:'to_review'})}<p class="form-note">I dati OCR sono proposte modificabili. Lo stato resta “Da controllare” finché non scegli diversamente.</p><button class="primary wide">Salva nel cloud</button></form></dialog><dialog id="complete-email-dialog"><form id="complete-email-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">PAGAMENTO FAMILIARE</p><h2>Completa i dati</h2></div><button type="button" class="icon-button" id="close-complete">${ico('X')}</button></div><input name="email_id" type="hidden"><label>Descrizione<input name="supplier" required maxlength="160"></label><label>Importo<input name="amount" type="number" min="0.01" step="0.01" required inputmode="decimal"></label><label>Scadenza<input name="due_on" type="date"></label><p class="form-note">La voce resterà DA PAGARE finché non confermi il pagamento.</p><button class="primary wide">Salva da pagare</button></form></dialog><dialog id="invoice-edit-dialog"><div id="invoice-edit-content"></div></dialog>`);
  const dialog=document.querySelector('#invoice-dialog'),form=document.querySelector('#invoice-form'),progress=document.querySelector('#ocr-progress'),completeDialog=document.querySelector('#complete-email-dialog'),completeForm=document.querySelector('#complete-email-form');let ocrResult=null;document.querySelector('#new-invoice').onclick=()=>dialog.showModal();document.querySelector('#close-dialog').onclick=()=>dialog.close();document.querySelector('#close-complete').onclick=()=>completeDialog.close();
  document.querySelectorAll('[data-complete-email]').forEach(button=>button.onclick=()=>{const message=pending.find(item=>item.id===button.dataset.completeEmail);if(!message)return;completeForm.elements.email_id.value=message.id;completeForm.elements.supplier.value=message.subject?.replace(/^Comunicazione\s+/i,'')||message.extracted_data?.supplier||'Pagamento familiare';completeForm.elements.amount.value='';completeForm.elements.due_on.value=message.extracted_data?.due_on||'';completeDialog.showModal()});
  completeForm.onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(completeForm)),message=pending.find(item=>item.id===values.email_id),submit=completeForm.querySelector('[type="submit"]');if(!message)return;submit.disabled=true;try{const invoice={id:crypto.randomUUID(),user_id:state.session.user.id,source_email_id:message.id,supplier:String(values.supplier).trim(),amount:Number(values.amount),due_on:values.due_on||null,status:'to_pay',confidence:1,extracted_data:{...(message.extracted_data||{}),supplier:String(values.supplier).trim(),amount:Number(values.amount),due_on:values.due_on||null,completed_manually:true},ocr_status:'not_requested'};const saved=await supabase.from('invoices').insert(invoice);if(saved.error)throw saved.error;completeDialog.close();state.notice='Pagamento aggiunto una sola volta tra le fatture da pagare.';await loadData()}catch(error){completeDialog.close();state.error=error.code==='23505'?'Questo pagamento è già presente nelle fatture.':error.message;render()}finally{submit.disabled=false}};
  form.elements.document.onchange=async()=>{const file=form.elements.document.files[0],fileError=validateInvoiceFile(file);ocrResult=null;if(!file){progress.hidden=true;return}if(fileError){state.error=fileError;dialog.close();render();return}progress.hidden=false;progress.textContent='OCR: preparazione…';try{const{extractInvoiceDocument}=await import('./ocr.js');ocrResult=await extractInvoiceDocument(file,(percent,label)=>{progress.textContent=`OCR: ${label}${percent?` · ${percent}%`:''}`});for(const[name,value]of Object.entries(ocrResult.extracted)){if(value!=null&&form.elements[name]&&!form.elements[name].value)form.elements[name].value=value}form.elements.status.value='to_review';progress.textContent=`OCR completato · affidabilità stimata ${Math.round(ocrResult.confidence*100)}% · controlla i dati prima di salvare`}catch(error){ocrResult={error:error.message};progress.textContent='OCR non riuscito: puoi comunque compilare e salvare manualmente.'}};
  form.onsubmit=async e=>{e.preventDefault();const form=e.target,submit=form.querySelector('[type="submit"]'),file=form.elements.document.files[0],fileError=validateInvoiceFile(file);if(fileError){state.error=fileError;dialog.close();render();return}submit.disabled=true;submit.textContent='Salvataggio…';let storagePath=null,invoiceId=crypto.randomUUID();try{const v=Object.fromEntries(new FormData(form));delete v.document;Object.assign(v,{id:invoiceId,user_id:state.session.user.id,amount:Number(v.amount)});for(const k of['invoice_number','iuv','issued_on','due_on'])if(!v[k])v[k]=null;if(file){v.file_hash=await fileHash(file);if(state.invoices.some(item=>item.file_hash===v.file_hash))throw new Error('Questo documento è già stato importato.');storagePath=`${state.session.user.id}/${invoiceId}/${storageFileName(file.name)}`;Object.assign(v,{storage_path:storagePath,document_name:file.name,document_mime:file.type,document_size:file.size,ocr_status:ocrResult?.text?'complete':ocrResult?.error?'failed':'not_requested',ocr_text:ocrResult?.text||null,extracted_data:ocrResult?.extracted||{},confidence:ocrResult?.confidence||null});const upload=await supabase.storage.from('invoice-documents').upload(storagePath,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error}const saved=await supabase.from('invoices').insert(v);if(saved.error)throw saved.error;if(file){const attachment=await supabase.from('attachments').insert({user_id:state.session.user.id,invoice_id:invoiceId,file_name:file.name,mime_type:file.type,byte_size:file.size,file_hash:v.file_hash,storage_path:storagePath});if(attachment.error){await supabase.from('invoices').delete().eq('id',invoiceId);await supabase.storage.from('invoice-documents').remove([storagePath]);throw attachment.error}}dialog.close();await loadData()}catch(error){if(storagePath)await supabase.storage.from('invoice-documents').remove([storagePath]);state.error=error.code==='23505'?'Fattura duplicata: controlla documento, IUV o numero fattura.':error.message;dialog.close();render()}finally{submit.disabled=false;submit.textContent='Salva nel cloud'}};bindJumps();bindInvoiceDocuments();bindInvoiceManagement();draw();
}
function summaryPage(){shell(`<article class="panel"><div class="panel-head"><div><p class="kicker">REGISTRO UNICO</p><h2>Tutte le operazioni</h2></div><span>${state.transactions.length} elementi</span></div>${txRows(state.transactions)}</article>`);draw()}
function deadlinesPage(){shell(`<article class="panel"><div class="panel-head"><div><p class="kicker">SCADENZE</p><h2>Fatture ancora aperte</h2></div></div>${invoiceRows(state.invoices.filter(i=>i.status==='to_pay'))}</article>`);bindInvoiceDocuments();draw()}
function statsPage(){
  const s=calculateSummary(state.transactions,state.invoices),insights=spendingInsights(state.transactions),progress=budgetProgress(state.transactions,state.budgets),max=Math.max(s.income,s.expenses,1),categoryMax=Math.max(1,...insights.categories.map(item=>item.amount)),change=insights.difference===0?'Uguali al mese precedente':insights.difference>0?`${money(insights.difference)} in più del mese precedente`:`${money(Math.abs(insights.difference))} in meno del mese precedente`;
  const categoryRows=insights.categories.length?insights.categories.map(item=>`<div><span>${safeText(item.name)}</span><div class="bar"><i class="expense" style="width:${item.amount/categoryMax*100}%"></i></div><b>${money(item.amount)}</b></div>`).join(''):empty('Nessuna spesa nel mese corrente.');
  const expenseCategories=state.categories.filter(category=>category.kind==='expense'||category.kind==='both'),budgetRows=expenseCategories.map(category=>{const current=progress.find(item=>item.category_id===category.id),spent=state.transactions.filter(row=>row.kind==='expense'&&!row.is_transfer&&row.category_id===category.id&&row.occurred_on?.startsWith(new Date().toISOString().slice(0,7))).reduce((sum,row)=>sum+Number(row.amount),0),percentage=current?Math.min(100,current.percentage):0;return`<div class="budget-row"><div><strong>${safeText(category.name)}</strong><small>${current?`${money(spent)} di ${money(current.limit)} · restano ${money(current.remaining)}`:`${money(spent)} spesi · limite non impostato`}</small></div><div class="budget-progress"><i class="${current?.status||''}" style="width:${percentage}%"></i></div><button class="document-button" data-budget-category="${category.id}">${current?'Modifica':'Imposta'}</button></div>`}).join('');
  shell(`<div class="metric-grid three">${metric('Entrate mese',money(s.income),'TrendingUp','positive')}${metric('Spese mese',money(s.expenses),'TrendingDown','negative')}${metric('Risparmio',money(s.savings),'PiggyBank',s.savings>=0?'positive':'negative')}</div><div class="content-grid"><article class="panel chart"><div class="panel-head"><div><p class="kicker">CONFRONTO MENSILE</p><h2>Entrate e spese</h2></div><small class="${insights.difference<=0?'positive':'negative'}">${change}</small></div><div><span>Entrate</span><div class="bar"><i style="width:${s.income/max*100}%"></i></div><b>${money(s.income)}</b></div><div><span>Spese</span><div class="bar"><i class="expense" style="width:${s.expenses/max*100}%"></i></div><b>${money(s.expenses)}</b></div></article><article class="panel chart category-chart"><div class="panel-head"><div><p class="kicker">SPESE FAMILIARI</p><h2>Per categoria</h2></div>${insights.top?`<small>Più alta: ${safeText(insights.top.name)}</small>`:''}</div>${categoryRows}</article></div><article class="panel budget-panel"><div class="panel-head"><div><p class="kicker">LIMITI MENSILI</p><h2>Budget familiare</h2></div><small>Avviso automatico all’80% e al 100%</small></div><div class="budget-list">${budgetRows}</div></article><dialog id="budget-dialog"><form id="budget-form" class="dialog-form"><div class="dialog-head"><div><p class="kicker">BUDGET MENSILE</p><h2 id="budget-title">Imposta limite</h2></div><button type="button" class="icon-button" id="close-budget">${ico('X')}</button></div><input type="hidden" name="category_id"><label>Limite mensile<input type="number" name="monthly_limit" min="1" step="1" inputmode="decimal" required></label><button class="primary wide">Salva budget</button><button class="secondary wide" type="button" id="delete-budget" hidden>Rimuovi limite</button></form></dialog>`);
  const dialog=document.querySelector('#budget-dialog'),form=document.querySelector('#budget-form'),remove=document.querySelector('#delete-budget');document.querySelector('#close-budget').onclick=()=>dialog.close();document.querySelectorAll('[data-budget-category]').forEach(button=>button.onclick=()=>{const category=state.categories.find(item=>item.id===button.dataset.budgetCategory),budget=state.budgets.find(item=>item.category_id===category.id);form.elements.category_id.value=category.id;form.elements.monthly_limit.value=budget?.monthly_limit||'';document.querySelector('#budget-title').textContent=category.name;remove.hidden=!budget;dialog.showModal()});form.onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(form)),result=await supabase.from('budgets').upsert({user_id:state.session.user.id,category_id:values.category_id,monthly_limit:Number(values.monthly_limit),updated_at:new Date().toISOString()},{onConflict:'user_id,category_id'});if(result.error){state.error=result.error.message;dialog.close();render()}else{dialog.close();state.notice='Budget mensile salvato.';await loadData()}};remove.onclick=async()=>{const categoryId=form.elements.category_id.value,result=await supabase.from('budgets').delete().eq('user_id',state.session.user.id).eq('category_id',categoryId);if(result.error){state.error=result.error.message;dialog.close();render()}else{dialog.close();state.notice='Limite mensile rimosso.';await loadData()}};draw()
}
function bankPage(){
  const rows=state.transactions.filter(item=>item.source==='bank'),linked=state.bankConnections.filter(item=>item.status==='linked'&&item.provider==='enablebanking'),bank=bankBalanceSummary(state.accounts),bankAccounts=bank.accounts;
  const connections=linked.length?`<div class="mail-accounts">${linked.map(connection=>{const accounts=bankAccounts.filter(account=>account.bank_connection_id===connection.id),remaining=connection.valid_until?Math.ceil((Date.parse(`${connection.valid_until}T23:59:59`)-Date.now())/86400000):null,needsRenewal=remaining!=null&&remaining<=14,accountLabels=accounts.map(account=>`${safeText(account.name)}${account.iban_last4?` •••• ${safeText(account.iban_last4)}`:''} · disponibile ${money(account.current_balance,account.currency||'EUR')}`).join('<br>');return`<article class="mail-account"><div class="row-icon income">${ico('Landmark')}</div><div><strong>${safeText(connection.institution_name)}</strong><small>${accounts.length} cont${accounts.length===1?'o':'i'}${accountLabels?`<br>${accountLabels}`:''}<br>${connection.last_synced_at?`aggiornata ${new Date(connection.last_synced_at).toLocaleString('it-IT')}`:'pronta alla sincronizzazione'}${connection.valid_until?` · autorizzazione fino al ${date(connection.valid_until)}`:''}</small></div>${needsRenewal?`<button class="primary" data-renew-bank="${connection.id}" data-institution="${safeText(connection.institution_id)}">${remaining<0?'Ricollega':'Rinnova'}</button>`:''}</article>`}).join('')}</div>`:'';
  const choices=state.bankInstitutions.length?`<article class="panel"><div class="panel-head"><div><p class="kicker">BANCHE DISPONIBILI</p><h2>Scegli il tuo istituto</h2></div><small>Puoi collegare più IBAN, anche della stessa banca.</small></div><div class="rows">${state.bankInstitutions.map(bank=>`<div class="row"><div class="row-icon">${ico('Building2')}</div><div><strong>${safeText(bank.name)}</strong><small>Autorizzazione sicura presso la banca</small></div><button class="primary" data-connect-bank="${safeText(bank.id)}">Collega un altro IBAN</button></div>`).join('')}</div></article>`:'';
  shell(`<div class="toolbar"><p>${bankAccounts.length} conti collegati · ${rows.length} movimenti · duplicati esclusi</p><div class="toolbar-actions"><button class="secondary" id="bank-file-button">${ico('FileUp')} CSV di riserva</button><input id="bank-file" type="file" accept=".csv,text/csv,text/plain" hidden>${linked.length?`<button class="secondary" id="sync-banks">${ico('RefreshCw')} Aggiorna</button>`:''}<button class="primary" id="load-banks">${ico('Link')} Collega un altro IBAN</button></div></div>${connections}${choices}<article class="panel"><div class="panel-head"><div><p class="kicker">RICONCILIAZIONE</p><h2>Pagamenti, fatture e trasferimenti</h2></div><small>Automatico solo con importo e riferimento forti</small></div>${rows.length?`<div class="rows">${rows.map(item=>`<div class="row"><div class="row-icon ${item.kind}">${ico(item.is_transfer?'ArrowLeftRight':item.kind==='income'?'ArrowDownLeft':'Landmark')}</div><div><strong>${safeText(item.description)}</strong><small>${date(item.occurred_on)} · ${item.is_transfer?'Trasferimento tra conti':item.reconciled?'Collegato a una fattura':item.transfer_status==='suggested'?'Possibile trasferimento da controllare':'Movimento bancario'}</small></div><div class="align-right"><b class="${item.is_transfer?'':item.kind==='income'?'positive':'negative'}">${item.is_transfer?'↔ ':item.kind==='income'?'+':'−'}${money(item.amount)}</b>${item.is_transfer?'<span class="badge paid">TRASFERIMENTO</span>':item.reconciled?'<span class="badge paid">RICONCILIATO</span>':item.transfer_status==='suggested'?`<div><button class="document-button" data-transfer-review="${item.id}" data-decision="confirm">È mio</button><button class="document-button negative" data-transfer-review="${item.id}" data-decision="reject">Non è mio</button></div>`:''}</div></div>`).join('')}</div>`:empty('Collega ING, UniCredit o Buddy Bank per leggere automaticamente i movimenti.')}</article>`);
  const input=document.querySelector('#bank-file'),fileButton=document.querySelector('#bank-file-button'),loadButton=document.querySelector('#load-banks');fileButton.onclick=()=>input.click();loadButton.onclick=async()=>{loadButton.disabled=true;loadButton.textContent='Ricerca banche…';const{data,error}=await supabase.functions.invoke('bank-institutions');if(error||!data?.institutions){state.error=await functionError(error,data?.error||'Impossibile leggere le banche disponibili.');render();return}state.bankInstitutions=data.institutions;render()};
  document.querySelectorAll('[data-connect-bank]').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='Apertura banca…';const{data,error}=await supabase.functions.invoke('bank-oauth-start',{body:{institution_id:button.dataset.connectBank}});if(error||!data?.url){state.error=await functionError(error,data?.error||'Impossibile iniziare il collegamento.');render();return}location.assign(data.url)});
  document.querySelectorAll('[data-renew-bank]').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='Apertura banca…';const{data,error}=await supabase.functions.invoke('bank-oauth-start',{body:{institution_id:button.dataset.institution,connection_id:button.dataset.renewBank,reconnect:true}});if(error||!data?.url){state.error=await functionError(error,data?.error||'Impossibile rinnovare il collegamento.');render();return}location.assign(data.url)});
  document.querySelectorAll('[data-transfer-review]').forEach(button=>button.onclick=async()=>{const id=button.dataset.transferReview,decision=button.dataset.decision;document.querySelectorAll(`[data-transfer-review="${id}"]`).forEach(item=>item.disabled=true);const{data,error}=await supabase.functions.invoke('bank-transfer-review',{body:{transaction_id:id,decision}});if(error||!data){state.error=await functionError(error,data?.error||'Impossibile salvare la scelta.');render();return}state.notice=decision==='confirm'?(data.learned?'Trasferimento confermato: questa carta o questo IBAN verrà riconosciuto anche in futuro.':'Trasferimento confermato ed escluso dalle spese.'):'Il movimento resterà una normale entrata o spesa.';await loadData()});
  const sync=document.querySelector('#sync-banks');if(sync)sync.onclick=()=>syncBanks(false);input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>2097152){state.error='Il CSV non può superare 2 MB.';render();return}const parsed=parseBankCsv(await file.text());if(parsed.error){state.error=parsed.error;render();return}if(!confirm(`Importare ${parsed.rows.length} movimenti? I duplicati verranno ignorati.`))return;fileButton.disabled=true;fileButton.textContent='Importazione…';const{data,error}=await supabase.functions.invoke('bank-import',{body:{rows:parsed.rows}});if(error||!data){state.error=await functionError(error,data?.error||'Importazione non riuscita.');render();return}state.notice=`Importati ${data.imported}; duplicati ignorati ${data.duplicates}; fatture pagate riconosciute ${data.matched}; da controllare ${data.review}.`;await loadData()};draw()
}
async function syncBanks(automatic=false){const{data,error}=await supabase.functions.invoke('bank-sync');if(error||!data){if(!automatic){state.error=await functionError(error,data?.error||'Aggiornamento bancario non riuscito.');render()}return}if(!automatic)state.notice=`Banche aggiornate: ${data.imported} nuovi movimenti, ${data.duplicates} già presenti, ${data.matched} fatture riconciliate.`;await loadData()}
const financialEmailLabels={paid:'PAGATA',to_pay:'DA PAGARE',to_review:'DA CONTROLLARE'};
async function functionError(error,fallback){try{return(error?.context&&await error.context.json())?.error||fallback}catch{return fallback}}
function applicationServerKey(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(character=>character.charCodeAt(0)))}
function pushAvailable(){return'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
async function enablePush(requestPermission){
  if(!pushAvailable())return false;
  if(requestPermission&&Notification.permission==='default')await Notification.requestPermission();
  if(Notification.permission!=='granted')return false;
  const registration=await navigator.serviceWorker.register('/sw.js');
  let subscription=await registration.pushManager.getSubscription();
  if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationServerKey(VAPID_PUBLIC_KEY)});
  const json=subscription.toJSON(),result=await supabase.from('push_subscriptions').upsert({user_id:state.session.user.id,endpoint:subscription.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()},{onConflict:'user_id,endpoint'});
  if(result.error)throw result.error;
  return true
}
async function syncRecentEmails(button=null,automatic=false){
  if(!state.session||!state.emailAccounts.length||state.gmailSyncing)return;
  state.gmailSyncing=true;
  if(button)button.disabled=true;
  let total=0,newUseful=0,hasMore=true,round=0;
  try{
    while(hasMore&&round<50){if(button)button.textContent=`Lettura dal giorno 1… ${total}`;const{data,error}=await supabase.functions.invoke('gmail-sync',{body:{restart:round===0}});if(error)throw new Error(await functionError(error,'Sincronizzazione Gmail non riuscita.'));total+=Number(data.imported||0);newUseful+=Number(data.newUseful||0);hasMore=Boolean(data.hasMore??data.has_more);round+=1}
    state.error='';if(!automatic)state.notice=hasMore?`${total} email elaborate. Premi di nuovo per continuare.`:`Mese corrente completato: ${total} email elaborate senza duplicati.`;
    if(newUseful>0&&Notification.permission==='granted'){const registration=await navigator.serviceWorker.ready;await registration.showNotification('SOLDI',{body:`${newUseful} nuove email finanziarie trovate.`,tag:'soldi-gmail-local',data:{url:'/?page=Email'}})}
  }catch(error){if(!automatic)state.error=error.message}
  finally{state.gmailSyncing=false;await loadData()}
}
function emailPage(){
  const financialCounts={paid:0,to_pay:0,to_review:0};state.emails.forEach(message=>{if(message.financial_status in financialCounts)financialCounts[message.financial_status]+=1});
  const invoiceEmailIds=new Set(state.invoices.map(invoice=>invoice.source_email_id).filter(Boolean));
  const accounts=state.emailAccounts.map(account=>`<article class="mail-account"><div class="row-icon income">${ico('MailCheck')}</div><div><strong>${safeText(account.email_address)}</strong><small>${account.last_synced_at?`Ultimo controllo ${new Date(account.last_synced_at).toLocaleString('it-IT')}`:'Pronto per la prima sincronizzazione'}</small></div></article>`).join('');
  const rows=state.emails.length?`<div class="rows">${state.emails.map(message=>{const extracted=message.extracted_data||{},linked=invoiceEmailIds.has(message.id),attachments=state.attachments.filter(item=>item.email_id===message.id);return`<div class="row email-row"><div class="row-icon">${ico(message.financial_status==='paid'?'BadgeCheck':message.financial_status==='to_pay'?'ReceiptText':'CircleAlert')}</div><div><strong>${safeText(message.subject||'(senza oggetto)')}</strong><small>${safeText(extracted.supplier||message.sender||'Mittente sconosciuto')} · ${message.received_at?new Date(message.received_at).toLocaleDateString('it-IT'):'—'}${extracted.amount?` · ${money(extracted.amount)}`:''}${extracted.due_on?` · scade ${date(extracted.due_on)}`:''}${attachments.length?` · ${attachments.length} allegat${attachments.length===1?'o':'i'}`:''}</small></div><div class="align-right"><span class="badge ${message.financial_status}">${financialEmailLabels[message.financial_status]}</span>${extracted.amount||attachments.length?`<button class="document-button" data-email-invoice="${message.id}" ${linked?'disabled':''}>${ico(linked?'Check':attachments.length?'ScanText':'FilePlus2')} ${linked?'In Fatture':attachments.length?`Analizza ${attachments.length} allegat${attachments.length===1?'o':'i'}`:'Aggiungi a Fatture'}</button>`:''}</div></div>`}).join('')}</div>`:empty('Nessun pagamento o documento da gestire trovato.');
  const pushLabel=!pushAvailable()?'Notifiche non supportate':Notification.permission==='granted'?'Notifiche attive':'Attiva notifiche';
  const alerts=state.notifications.length?`<article class="panel"><div class="panel-head"><div><p class="kicker">NOVITÀ</p><h2>${state.notifications.length} notifiche non lette</h2></div><button id="read-notifications">Segna come lette</button></div>${state.notifications.map(item=>`<p><strong>${safeText(item.title)}</strong><br><small>${safeText(item.body)}</small></p>`).join('')}</article>`:'';
  shell(`<div class="toolbar"><p>${state.emailAccounts.length} account Gmail · ${state.emails.length} risultati finanziari</p><div class="toolbar-actions"><button class="secondary" id="connect-gmail">${ico('Link')} Collega Gmail</button>${state.emailAccounts.length?`<button class="secondary" id="push-notifications" ${!pushAvailable()?'disabled':''}>${ico('Bell')} ${pushLabel}</button><button class="primary" id="sync-gmail">${ico('RefreshCw')} Sincronizza dal giorno 1</button>`:''}</div></div>${alerts}${accounts?`<div class="mail-accounts">${accounts}</div>`:''}<article class="panel table-panel"><div class="panel-head email-head"><div><p class="kicker">RISULTATI FINANZIARI</p><h2>Mese corrente</h2><small>${financialCounts.paid} pagate · ${financialCounts.to_pay} da pagare · ${financialCounts.to_review} da controllare</small></div><small>Controllo automatico all’apertura e ogni giorno alle 17:00 · email normali escluse</small></div>${rows}</article>`);
  document.querySelector('#connect-gmail').onclick=async()=>{state.error='';state.notice='';const button=document.querySelector('#connect-gmail');button.disabled=true;button.textContent='Apertura Google…';const{data,error}=await supabase.functions.invoke('gmail-oauth-start');if(error||!data?.url){state.error=await functionError(error,'Impossibile avviare il collegamento Gmail.');render();return}location.assign(data.url)};
  const sync=document.querySelector('#sync-gmail');if(sync)sync.onclick=()=>{state.error='';state.notice='';syncRecentEmails(sync,false)};
  const push=document.querySelector('#push-notifications');if(push)push.onclick=async()=>{try{push.disabled=true;const active=await enablePush(true);state.notice=active?'Notifiche attivate su questo dispositivo.':'Per ricevere notifiche devi consentirle nelle impostazioni del browser.';render()}catch(error){state.error=error.message;render()}};
  const read=document.querySelector('#read-notifications');if(read)read.onclick=async()=>{const{error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',state.session.user.id).is('read_at',null);if(error){state.error=error.message;render()}else await loadData()};draw();
  document.querySelectorAll('[data-email-invoice]').forEach(button=>button.onclick=async()=>{const message=state.emails.find(item=>item.id===button.dataset.emailInvoice),attachments=state.attachments.filter(item=>item.email_id===message?.id);if(!message)return;button.disabled=true;button.textContent=attachments.length?`Analisi ${attachments.length} allegati…`:'Aggiunta…';try{const ocrResults=[];if(attachments.length){const{extractInvoiceDocument}=await import('./ocr.js');for(const attachment of attachments){const downloaded=await supabase.storage.from('invoice-documents').download(attachment.storage_path);if(downloaded.error)throw downloaded.error;const file=new File([downloaded.data],attachment.file_name,{type:attachment.mime_type||downloaded.data.type});ocrResults.push(await extractInvoiceDocument(file))}}const merged=mergeFinancialExtractions(message.extracted_data||{},ocrResults),extracted=merged.extracted;if(!Number(extracted.amount))throw new Error('Non trovo un importo certo negli allegati: la voce resta Da controllare.');const primary=attachments[0],invoiceId=crypto.randomUUID(),ocrText=ocrResults.map(result=>result.text).filter(Boolean).join('\n\n--- ALLEGATO SUCCESSIVO ---\n\n'),invoice={id:invoiceId,user_id:state.session.user.id,source_email_id:message.id,supplier:extracted.supplier||message.sender||'Fornitore da verificare',amount:Number(extracted.amount),invoice_number:extracted.invoice_number||null,iuv:extracted.iuv||null,issued_on:extracted.issued_on||null,due_on:extracted.due_on||null,status:message.financial_status,confidence:merged.confidence||message.confidence||null,extracted_data:{...extracted,attachment_count:attachments.length},ocr_status:ocrText?'complete':'not_requested',ocr_text:ocrText||null,storage_path:primary?.storage_path||null,document_name:primary?.file_name||null,document_mime:primary?.mime_type||null,document_size:primary?.byte_size||null,file_hash:primary?.file_hash||null};const saved=await supabase.from('invoices').insert(invoice);if(saved.error)throw saved.error;if(attachments.length){const linked=await supabase.from('attachments').update({invoice_id:invoiceId}).in('id',attachments.map(item=>item.id)).eq('user_id',state.session.user.id);if(linked.error){await supabase.from('invoices').delete().eq('id',invoiceId);throw linked.error}}state.notice=`${attachments.length} allegati analizzati e uniti in una sola fattura.`;state.page='Fatture';await loadData()}catch(error){state.error=error.code==='23505'?'Questa email o uno dei documenti è già collegato a una fattura.':error.message;render()}});
  const automaticAttachment=[...document.querySelectorAll('[data-email-invoice]')].find(button=>{const message=state.emails.find(item=>item.id===button.dataset.emailInvoice);return message?.financial_status==='to_pay'&&!Number(message.extracted_data?.amount)&&!invoiceEmailIds.has(message.id)&&!state.autoOcrAttempted.has(message.id)&&state.attachments.some(item=>item.email_id===message.id)});if(automaticAttachment){state.autoOcrAttempted.add(automaticAttachment.dataset.emailInvoice);setTimeout(()=>automaticAttachment.click(),400)}
}
function placeholder(title,copy,glyph){shell(`<article class="panel placeholder"><div class="placeholder-icon">${ico(glyph)}</div><p class="kicker">MODULO PREPARATO</p><h2>${title}</h2><p>${copy}</p></article>`);draw()}
function backupPage(){shell(`<article class="panel backup-card"><div class="placeholder-icon">${ico('DatabaseBackup')}</div><p class="kicker">COPIA PERSONALE</p><h2>Backup dei tuoi dati SOLDI</h2><p>Scarica movimenti, fatture, scadenze, categorie e budget in un unico file JSON. Password, credenziali bancarie, token Gmail e notifiche del telefono non vengono esportati.</p><button class="primary" id="download-backup">${ico('Download')} Scarica backup</button><small>I PDF e le foto restano protetti nello spazio documenti e non sono inclusi nel file.</small></article>`);const button=document.querySelector('#download-backup');button.onclick=async()=>{button.disabled=true;button.textContent='Preparazione backup…';const{data,error}=await supabase.functions.invoke('data-export');if(error||!data?.data){state.error=await functionError(error,data?.error||'Impossibile creare il backup.');render();return}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`SOLDI-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);state.notice='Backup scaricato sul dispositivo.';render()};draw()}
function render(){if(!state.session)return authView();const routes={Home:home,Fatture:invoicesPage,Entrate:()=>transactionPage('income'),Spese:()=>transactionPage('expense'),'Da classificare':classificationPage,Riepilogo:summaryPage,Scadenze:deadlinesPage,Statistiche:statsPage,Email:emailPage,Banca:bankPage,Backup:backupPage,Impostazioni:()=>placeholder('Impostazioni','Profilo, categorie, collegamenti e preferenze personali.','Settings')};(routes[state.page]||home)()}

const callback=new URLSearchParams(location.search);if(callback.get('page')==='Email')state.page='Email';if(callback.get('page')==='Banca')state.page='Banca';if(callback.has('gmail')){state.page='Email';if(callback.get('gmail')==='connected')state.notice='Account Gmail collegato correttamente.';else state.error=callback.get('detail')||'Collegamento Gmail non riuscito.';history.replaceState({},'',location.pathname)}if(callback.has('bank')){state.page='Banca';if(callback.get('bank')==='connected')state.notice='Banca collegata correttamente.';else state.error=callback.get('detail')||'Collegamento bancario non riuscito.';history.replaceState({},'',location.pathname)}
if(supabase){supabase.auth.getSession().then(({data})=>{state.session=data.session;if(state.session)loadData();else render()});supabase.auth.onAuthStateChange((event,session)=>{state.session=session;if(event==='SIGNED_IN')setTimeout(loadData,0);else{state.autoSyncStarted=false;state.bankSyncStarted=false;render()}})}else render();
